<?php

namespace Database\Seeders;

use App\Domains\FormOptions\Models\FormOption;
use Illuminate\Database\Seeder;

class FormOptionSeeder extends Seeder
{
    /**
     * @return array<int, array<string, mixed>>
     */
    private function options(): array
    {
        return [
            // ── gender — جنسیت
            ['group' => 'gender', 'value' => 'male', 'label' => 'مرد', 'sort_order' => 1],
            ['group' => 'gender', 'value' => 'female', 'label' => 'زن', 'sort_order' => 2],

            // ── blood_group — گروه خونی
            ['group' => 'blood_group', 'value' => 'A+', 'label' => 'A+', 'sort_order' => 1],
            ['group' => 'blood_group', 'value' => 'A-', 'label' => 'A-', 'sort_order' => 2],
            ['group' => 'blood_group', 'value' => 'B+', 'label' => 'B+', 'sort_order' => 3],
            ['group' => 'blood_group', 'value' => 'B-', 'label' => 'B-', 'sort_order' => 4],
            ['group' => 'blood_group', 'value' => 'AB+', 'label' => 'AB+', 'sort_order' => 5],
            ['group' => 'blood_group', 'value' => 'AB-', 'label' => 'AB-', 'sort_order' => 6],
            ['group' => 'blood_group', 'value' => 'O+', 'label' => 'O+', 'sort_order' => 7],
            ['group' => 'blood_group', 'value' => 'O-', 'label' => 'O-', 'sort_order' => 8],

            // ── spouse_employment_status — وضعیت اشتغال همسر
            ['group' => 'spouse_employment_status', 'value' => 'employed', 'label' => 'شاغل', 'sort_order' => 1],
            ['group' => 'spouse_employment_status', 'value' => 'housewife', 'label' => 'خانه‌دار', 'sort_order' => 2],

            // ── military_status — وضعیت نظام وظیفه
            ['group' => 'military_status', 'value' => 'completed', 'label' => 'پایان خدمت', 'sort_order' => 1],
            ['group' => 'military_status', 'value' => 'amrieh', 'label' => 'امریه', 'sort_order' => 2],
            ['group' => 'military_status', 'value' => 'guardian_exemption', 'label' => 'معافیت کفالت', 'sort_order' => 3],
            ['group' => 'military_status', 'value' => 'medical_exemption', 'label' => 'معافیت پزشکی', 'sort_order' => 4],
            ['group' => 'military_status', 'value' => 'education_exemption', 'label' => 'معافیت تحصیلی', 'sort_order' => 5],
            ['group' => 'military_status', 'value' => 'leader_pardon', 'label' => 'عفو رهبری', 'sort_order' => 6],
            ['group' => 'military_status', 'value' => 'service_purchase', 'label' => 'خرید خدمت', 'sort_order' => 7],
            ['group' => 'military_status', 'value' => 'other', 'label' => 'سایر', 'sort_order' => 8],

            // ── employment_type — نوع همکاری
            ['group' => 'employment_type', 'value' => 'full_time', 'label' => 'تمام وقت', 'sort_order' => 1],
            ['group' => 'employment_type', 'value' => 'part_time', 'label' => 'پاره وقت', 'sort_order' => 2],

            // ── preferred_workplace — محل کار ترجیحی
            ['group' => 'preferred_workplace', 'value' => 'tehran', 'label' => 'دفتر تهران', 'sort_order' => 1],
            ['group' => 'preferred_workplace', 'value' => 'kerman', 'label' => 'دفتر کرمان', 'sort_order' => 2],
            ['group' => 'preferred_workplace', 'value' => 'site', 'label' => 'سایت', 'sort_order' => 3],
            ['group' => 'preferred_workplace', 'value' => 'other', 'label' => 'سایر', 'sort_order' => 4],

            // ── religion — دین (ریشه‌ها)
            ['group' => 'religion', 'value' => 'islam', 'label' => 'اسلام', 'sort_order' => 1],
            ['group' => 'religion', 'value' => 'christian', 'label' => 'مسیحی', 'sort_order' => 2],
            ['group' => 'religion', 'value' => 'jewish', 'label' => 'کلیمی', 'sort_order' => 3],
            ['group' => 'religion', 'value' => 'zoroastrian', 'label' => 'زرتشتی', 'sort_order' => 4],

            // ── religion_sect — مذهب (وابسته به دین از طریق parent_value)
            ['group' => 'religion_sect', 'value' => 'sunni', 'label' => 'سنی', 'parent_value' => 'islam', 'sort_order' => 1],
            ['group' => 'religion_sect', 'value' => 'shia', 'label' => 'شیعه', 'parent_value' => 'islam', 'sort_order' => 2],
            ['group' => 'religion_sect', 'value' => 'catholic', 'label' => 'کاتولیک', 'parent_value' => 'christian', 'sort_order' => 1],
            ['group' => 'religion_sect', 'value' => 'orthodox', 'label' => 'ارتودوکس', 'parent_value' => 'christian', 'sort_order' => 2],
            ['group' => 'religion_sect', 'value' => 'protestant', 'label' => 'پروتستان', 'parent_value' => 'christian', 'sort_order' => 3],
            ['group' => 'religion_sect', 'value' => 'zoroastrian', 'label' => 'زرتشتی', 'parent_value' => 'zoroastrian', 'sort_order' => 1],
            ['group' => 'religion_sect', 'value' => 'jewish', 'label' => 'کلیمی', 'parent_value' => 'jewish', 'sort_order' => 1],

            // ── cooperation_type — نوع همکاری مورد نظر
            ['group' => 'cooperation_type', 'value' => 'full_time', 'label' => 'تمام وقت', 'sort_order' => 1],
            ['group' => 'cooperation_type', 'value' => 'part_time', 'label' => 'پاره وقت', 'sort_order' => 2],
            ['group' => 'cooperation_type', 'value' => 'intern', 'label' => 'کارآموز', 'sort_order' => 3],

            // ── insurance_type — نوع بیمه
            ['group' => 'insurance_type', 'value' => 'social_security', 'label' => 'تامین اجتماعی', 'sort_order' => 1],
            ['group' => 'insurance_type', 'value' => 'supplementary', 'label' => 'بیمه تکمیلی', 'sort_order' => 2],
            ['group' => 'insurance_type', 'value' => 'private', 'label' => 'بیمه خصوصی', 'sort_order' => 3],

            // ── physical_condition — وضعیت جسمانی
            ['group' => 'physical_condition', 'value' => 'healthy', 'label' => 'سالم', 'sort_order' => 1],
            ['group' => 'physical_condition', 'value' => 'sick', 'label' => 'بیمار', 'sort_order' => 2],
            ['group' => 'physical_condition', 'value' => 'disabled', 'label' => 'معلول', 'sort_order' => 3],
            ['group' => 'physical_condition', 'value' => 'severely_disabled', 'label' => 'معلول شدید', 'sort_order' => 4],

            // ── marital_status — وضعیت تأهل
            ['group' => 'marital_status', 'value' => 'single', 'label' => 'مجرد', 'sort_order' => 1],
            ['group' => 'marital_status', 'value' => 'married', 'label' => 'متاهل', 'sort_order' => 2],
            ['group' => 'marital_status', 'value' => 'divorced', 'label' => 'طلاق گرفته', 'sort_order' => 3],
            ['group' => 'marital_status', 'value' => 'widowed', 'label' => 'همسر فوت شده', 'sort_order' => 4],
            ['group' => 'marital_status', 'value' => 'unknown', 'label' => 'نامشخص', 'sort_order' => 5],

            // ── relationship_type — نوع رابطه وابستگی (بستگان کارمند)
            ['group' => 'relationship_type', 'value' => 'spouse', 'label' => 'همسر', 'sort_order' => 1],
            ['group' => 'relationship_type', 'value' => 'child', 'label' => 'فرزند', 'sort_order' => 2],
            ['group' => 'relationship_type', 'value' => 'father', 'label' => 'پدر', 'sort_order' => 3],
            ['group' => 'relationship_type', 'value' => 'mother', 'label' => 'مادر', 'sort_order' => 4],
            ['group' => 'relationship_type', 'value' => 'other', 'label' => 'سایر', 'sort_order' => 5],

            // ── inquiry_status — وضعیت استعلام مدارک (بخش استعلام مدارک؛
            //    مقادیر در حال تغییر هستند و از طریق FormOptions قابل ویرایش‌اند)
            ['group' => 'inquiry_status', 'value' => 'pending', 'label' => 'در انتظار استعلام', 'sort_order' => 1],
            ['group' => 'inquiry_status', 'value' => 'received', 'label' => 'پاسخ دریافت شد', 'sort_order' => 2],
            ['group' => 'inquiry_status', 'value' => 'mismatch', 'label' => 'مغایرت دارد', 'sort_order' => 3],

            // ── property_status — وضعیت ملک
            ['group' => 'property_status', 'value' => 'owned', 'label' => 'شخصی', 'sort_order' => 1],
            ['group' => 'property_status', 'value' => 'rented', 'label' => 'استیجاری', 'sort_order' => 2],
            ['group' => 'property_status', 'value' => 'parental', 'label' => 'ملک پدری', 'sort_order' => 3],
            ['group' => 'property_status', 'value' => 'organizational', 'label' => 'سازمانی', 'sort_order' => 4],

            // ── seniority_level — سطح ارشدیت
            ['group' => 'seniority_level', 'value' => 'intern', 'label' => 'کارآموز', 'sort_order' => 1],
            ['group' => 'seniority_level', 'value' => 'junior', 'label' => 'تازه‌کار', 'sort_order' => 2],
            ['group' => 'seniority_level', 'value' => 'mid_level', 'label' => 'متوسط', 'sort_order' => 3],
            ['group' => 'seniority_level', 'value' => 'senior', 'label' => 'ارشد', 'sort_order' => 4],
            ['group' => 'seniority_level', 'value' => 'specialist', 'label' => 'متخصص', 'sort_order' => 5],
            ['group' => 'seniority_level', 'value' => 'manager', 'label' => 'مدیر', 'sort_order' => 6],
            ['group' => 'seniority_level', 'value' => 'senior_manager', 'label' => 'مدیر ارشد', 'sort_order' => 7],
            ['group' => 'seniority_level', 'value' => 'director', 'label' => 'مدیرعامل / عضو هیئت مدیره', 'sort_order' => 8],

            // ── contract_type — نوع قرارداد
            ['group' => 'contract_type', 'value' => 'full_time', 'label' => 'تمام‌وقت', 'sort_order' => 1],
            ['group' => 'contract_type', 'value' => 'part_time', 'label' => 'پاره‌وقت', 'sort_order' => 2],
            ['group' => 'contract_type', 'value' => 'remote', 'label' => 'دورکاری', 'sort_order' => 3],
            ['group' => 'contract_type', 'value' => 'internship', 'label' => 'کارآموزی', 'sort_order' => 4],
            ['group' => 'contract_type', 'value' => 'contractual', 'label' => 'قراردادی', 'sort_order' => 5],
            ['group' => 'contract_type', 'value' => 'project_based', 'label' => 'پروژه‌ای', 'sort_order' => 6],
            ['group' => 'contract_type', 'value' => 'freelance', 'label' => 'فریلنسری', 'sort_order' => 7],

            // ── termination_reason — علت قطع همکاری
            ['group' => 'termination_reason', 'value' => 'bad_work_environment', 'label' => 'شرایط نامساعد محیط کار', 'sort_order' => 1],
            ['group' => 'termination_reason', 'value' => 'no_promotion', 'label' => 'نبود فرصت ارتقاء یا رشد محدود شغلی', 'sort_order' => 2],
            ['group' => 'termination_reason', 'value' => 'harmful_job', 'label' => 'سختی و زیان آور بودن شغل', 'sort_order' => 3],
            ['group' => 'termination_reason', 'value' => 'bad_culture', 'label' => 'نارضایتی از فرهنگ سازمانی', 'sort_order' => 4],
            ['group' => 'termination_reason', 'value' => 'relocation', 'label' => 'تغییر محل سکونت', 'sort_order' => 5],
            ['group' => 'termination_reason', 'value' => 'bad_hours', 'label' => 'نارضایتی از ساعات کاری', 'sort_order' => 6],
            ['group' => 'termination_reason', 'value' => 'bad_job_type', 'label' => 'نارضایتی از نوع کار (غنی نبودن شغل)', 'sort_order' => 7],
            ['group' => 'termination_reason', 'value' => 'job_stress', 'label' => 'استرس شغلی', 'sort_order' => 8],
            ['group' => 'termination_reason', 'value' => 'bad_manager', 'label' => 'نارضایتی از مدیر مربوطه', 'sort_order' => 9],
            ['group' => 'termination_reason', 'value' => 'emigration', 'label' => 'عزیمت به خارج از کشور', 'sort_order' => 10],
            ['group' => 'termination_reason', 'value' => 'no_job_security', 'label' => 'عدم احساس امنیت شغلی', 'sort_order' => 11],
            ['group' => 'termination_reason', 'value' => 'pregnancy', 'label' => 'بارداری و زایمان', 'sort_order' => 12],
            ['group' => 'termination_reason', 'value' => 'high_workload', 'label' => 'نارضایتی از حجم کار زیاد', 'sort_order' => 13],
            ['group' => 'termination_reason', 'value' => 'low_salary', 'label' => 'نارضایتی از میزان دریافتی', 'sort_order' => 14],
            ['group' => 'termination_reason', 'value' => 'company_no_need', 'label' => 'عدم نیاز شرکت', 'sort_order' => 15],
            ['group' => 'termination_reason', 'value' => 'no_growth', 'label' => 'نبود یا کمبود فرصت رشد و توسعه فردی', 'sort_order' => 16],
            ['group' => 'termination_reason', 'value' => 'company_dissatisfied', 'label' => 'نارضایتی شرکت/ مدیر از عملکرد/ رفتار فرد', 'sort_order' => 17],
            ['group' => 'termination_reason', 'value' => 'entrepreneurship', 'label' => 'کارآفرینی', 'sort_order' => 18],
            ['group' => 'termination_reason', 'value' => 'retirement', 'label' => 'بازنشستگی', 'sort_order' => 19],
            ['group' => 'termination_reason', 'value' => 'contract_end', 'label' => 'پایان قرارداد', 'sort_order' => 20],
            ['group' => 'termination_reason', 'value' => 'layoff', 'label' => 'تعدیل نیرو / ادغام', 'sort_order' => 21],
            ['group' => 'termination_reason', 'value' => 'career_change', 'label' => 'تغییر مسیر شغلی', 'sort_order' => 22],
            ['group' => 'termination_reason', 'value' => 'personal_reasons', 'label' => 'دلایل شخصی', 'sort_order' => 23],
            ['group' => 'termination_reason', 'value' => 'better_offer', 'label' => 'پیشنهاد شغلی بهتر', 'sort_order' => 24],

            // ── degree — مدرک تحصیلی
            ['group' => 'degree', 'value' => 'below_diploma', 'label' => 'زیر دیپلم', 'sort_order' => 1],
            ['group' => 'degree', 'value' => 'diploma', 'label' => 'دیپلم', 'sort_order' => 2],
            ['group' => 'degree', 'value' => 'associate', 'label' => 'کاردانی', 'sort_order' => 3],
            ['group' => 'degree', 'value' => 'bachelor', 'label' => 'کارشناسی', 'sort_order' => 4],
            ['group' => 'degree', 'value' => 'master', 'label' => 'کارشناسی ارشد', 'sort_order' => 5],
            ['group' => 'degree', 'value' => 'doctorate', 'label' => 'دکترا', 'sort_order' => 6],

            // ── university — دانشگاه
            ['group' => 'university', 'value' => 'tehran', 'label' => 'دانشگاه تهران', 'sort_order' => 1],
            ['group' => 'university', 'value' => 'sharif', 'label' => 'دانشگاه صنعتی شریف', 'sort_order' => 2],
            ['group' => 'university', 'value' => 'amirkabir', 'label' => 'دانشگاه صنعتی امیرکبیر', 'sort_order' => 3],
            ['group' => 'university', 'value' => 'iust', 'label' => 'دانشگاه علم و صنعت ایران', 'sort_order' => 4],
            ['group' => 'university', 'value' => 'khajeh_nasir', 'label' => 'دانشگاه خواجه نصیرالدین طوسی', 'sort_order' => 5],
            ['group' => 'university', 'value' => 'shahid_beheshti', 'label' => 'دانشگاه شهید بهشتی', 'sort_order' => 6],
            ['group' => 'university', 'value' => 'allameh', 'label' => 'دانشگاه علامه طباطبائی', 'sort_order' => 7],
            ['group' => 'university', 'value' => 'alzahra', 'label' => 'دانشگاه الزهرا (س)', 'sort_order' => 8],
            ['group' => 'university', 'value' => 'tarbiat_modares', 'label' => 'دانشگاه تربیت مدرس', 'sort_order' => 9],
            ['group' => 'university', 'value' => 'art_tehran', 'label' => 'دانشگاه هنر تهران', 'sort_order' => 10],
            ['group' => 'university', 'value' => 'isfahan_tech', 'label' => 'دانشگاه صنعتی اصفهان', 'sort_order' => 11],
            ['group' => 'university', 'value' => 'isfahan', 'label' => 'دانشگاه اصفهان', 'sort_order' => 12],
            ['group' => 'university', 'value' => 'shiraz', 'label' => 'دانشگاه شیراز', 'sort_order' => 13],
            ['group' => 'university', 'value' => 'shiraz_tech', 'label' => 'دانشگاه صنعتی شیراز', 'sort_order' => 14],
            ['group' => 'university', 'value' => 'ferdowsi', 'label' => 'دانشگاه فردوسی مشهد', 'sort_order' => 15],
            ['group' => 'university', 'value' => 'tabriz', 'label' => 'دانشگاه تبریز', 'sort_order' => 16],
            ['group' => 'university', 'value' => 'sahand', 'label' => 'دانشگاه صنعتی سهند', 'sort_order' => 17],
            ['group' => 'university', 'value' => 'chamran', 'label' => 'دانشگاه شهید چمران اهواز', 'sort_order' => 18],
            ['group' => 'university', 'value' => 'razi', 'label' => 'دانشگاه رازی کرمانشاه', 'sort_order' => 19],
            ['group' => 'university', 'value' => 'bu_ali', 'label' => 'دانشگاه بوعلی سینا همدان', 'sort_order' => 20],
            ['group' => 'university', 'value' => 'kurdistan', 'label' => 'دانشگاه کردستان', 'sort_order' => 21],
            ['group' => 'university', 'value' => 'mazandaran', 'label' => 'دانشگاه مازندران', 'sort_order' => 22],
            ['group' => 'university', 'value' => 'guilan', 'label' => 'دانشگاه گیلان', 'sort_order' => 23],
            ['group' => 'university', 'value' => 'urmia', 'label' => 'دانشگاه ارومیه', 'sort_order' => 24],
            ['group' => 'university', 'value' => 'yazd', 'label' => 'دانشگاه یزد', 'sort_order' => 25],
            ['group' => 'university', 'value' => 'bahonar', 'label' => 'دانشگاه شهید باهنر کرمان', 'sort_order' => 26],
            ['group' => 'university', 'value' => 'sistan', 'label' => 'دانشگاه سیستان و بلوچستان', 'sort_order' => 27],
            ['group' => 'university', 'value' => 'hormozgan', 'label' => 'دانشگاه هرمزگان', 'sort_order' => 28],
            ['group' => 'university', 'value' => 'birjand', 'label' => 'دانشگاه بیرجند', 'sort_order' => 29],
            ['group' => 'university', 'value' => 'semnan', 'label' => 'دانشگاه سمنان', 'sort_order' => 30],
            ['group' => 'university', 'value' => 'qom', 'label' => 'دانشگاه قم', 'sort_order' => 31],
            ['group' => 'university', 'value' => 'araki', 'label' => 'دانشگاه اراک', 'sort_order' => 32],
            ['group' => 'university', 'value' => 'lorestan', 'label' => 'دانشگاه لرستان', 'sort_order' => 33],
            ['group' => 'university', 'value' => 'zanjan', 'label' => 'دانشگاه زنجان', 'sort_order' => 34],
            ['group' => 'university', 'value' => 'golestan', 'label' => 'دانشگاه گلستان', 'sort_order' => 35],
            ['group' => 'university', 'value' => 'yasouj', 'label' => 'دانشگاه یاسوج', 'sort_order' => 36],
            ['group' => 'university', 'value' => 'shahrekord', 'label' => 'دانشگاه شهرکرد', 'sort_order' => 37],
            ['group' => 'university', 'value' => 'noushirvani', 'label' => 'دانشگاه صنعتی نوشیروانی بابل', 'sort_order' => 38],
            ['group' => 'university', 'value' => 'jundi_shapur', 'label' => 'دانشگاه صنعتی جندی‌شاپور دزفول', 'sort_order' => 39],
            ['group' => 'university', 'value' => 'shahrood', 'label' => 'دانشگاه صنعتی شاهرود', 'sort_order' => 40],
            ['group' => 'university', 'value' => 'kharazmi', 'label' => 'دانشگاه خوارزمی', 'sort_order' => 41],
            ['group' => 'university', 'value' => 'imam_khomeini', 'label' => 'دانشگاه بین‌المللی امام خمینی (ره)', 'sort_order' => 42],
            ['group' => 'university', 'value' => 'payame_noor', 'label' => 'دانشگاه پیام نور', 'sort_order' => 43],
            ['group' => 'university', 'value' => 'azad', 'label' => 'دانشگاه آزاد اسلامی', 'sort_order' => 44],
            ['group' => 'university', 'value' => 'elmi_karbordi', 'label' => 'دانشگاه جامع علمی و کاربردی', 'sort_order' => 45],
            ['group' => 'university', 'value' => 'fanni_herfei', 'label' => 'دانشگاه فنی و حرفه‌ای', 'sort_order' => 46],
            ['group' => 'university', 'value' => 'farhangian', 'label' => 'دانشگاه فرهنگیان', 'sort_order' => 47],
            ['group' => 'university', 'value' => 'other', 'label' => 'سایر', 'sort_order' => 48],

            // ── field_of_study — رشته تحصیلی
            ['group' => 'field_of_study', 'value' => 'computer_engineering', 'label' => 'مهندسی کامپیوتر', 'sort_order' => 1],
            ['group' => 'field_of_study', 'value' => 'information_technology', 'label' => 'مهندسی فناوری اطلاعات', 'sort_order' => 2],
            ['group' => 'field_of_study', 'value' => 'software_engineering', 'label' => 'مهندسی نرم‌افزار', 'sort_order' => 3],
            ['group' => 'field_of_study', 'value' => 'electrical_engineering', 'label' => 'مهندسی برق', 'sort_order' => 4],
            ['group' => 'field_of_study', 'value' => 'mechanical_engineering', 'label' => 'مهندسی مکانیک', 'sort_order' => 5],
            ['group' => 'field_of_study', 'value' => 'civil_engineering', 'label' => 'مهندسی عمران', 'sort_order' => 6],
            ['group' => 'field_of_study', 'value' => 'industrial_engineering', 'label' => 'مهندسی صنایع', 'sort_order' => 7],
            ['group' => 'field_of_study', 'value' => 'chemical_engineering', 'label' => 'مهندسی شیمی', 'sort_order' => 8],
            ['group' => 'field_of_study', 'value' => 'materials_engineering', 'label' => 'مهندسی مواد', 'sort_order' => 9],
            ['group' => 'field_of_study', 'value' => 'architecture', 'label' => 'معماری', 'sort_order' => 10],
            ['group' => 'field_of_study', 'value' => 'accounting', 'label' => 'حسابداری', 'sort_order' => 11],
            ['group' => 'field_of_study', 'value' => 'business_administration', 'label' => 'مدیریت بازرگانی', 'sort_order' => 12],
            ['group' => 'field_of_study', 'value' => 'industrial_management', 'label' => 'مدیریت صنعتی', 'sort_order' => 13],
            ['group' => 'field_of_study', 'value' => 'economics', 'label' => 'اقتصاد', 'sort_order' => 14],
            ['group' => 'field_of_study', 'value' => 'finance', 'label' => 'مالی', 'sort_order' => 15],
            ['group' => 'field_of_study', 'value' => 'mathematics', 'label' => 'ریاضیات', 'sort_order' => 16],
            ['group' => 'field_of_study', 'value' => 'statistics', 'label' => 'آمار', 'sort_order' => 17],
            ['group' => 'field_of_study', 'value' => 'physics', 'label' => 'فیزیک', 'sort_order' => 18],
            ['group' => 'field_of_study', 'value' => 'chemistry', 'label' => 'شیمی', 'sort_order' => 19],
            ['group' => 'field_of_study', 'value' => 'biology', 'label' => 'زیست‌شناسی', 'sort_order' => 20],
            ['group' => 'field_of_study', 'value' => 'medicine', 'label' => 'پزشکی', 'sort_order' => 21],
            ['group' => 'field_of_study', 'value' => 'nursing', 'label' => 'پرستاری', 'sort_order' => 22],
            ['group' => 'field_of_study', 'value' => 'pharmacy', 'label' => 'داروسازی', 'sort_order' => 23],
            ['group' => 'field_of_study', 'value' => 'psychology', 'label' => 'روان‌شناسی', 'sort_order' => 24],
            ['group' => 'field_of_study', 'value' => 'sociology', 'label' => 'جامعه‌شناسی', 'sort_order' => 25],
            ['group' => 'field_of_study', 'value' => 'law', 'label' => 'حقوق', 'sort_order' => 26],
            ['group' => 'field_of_study', 'value' => 'political_science', 'label' => 'علوم سیاسی', 'sort_order' => 27],
            ['group' => 'field_of_study', 'value' => 'persian_literature', 'label' => 'زبان و ادبیات فارسی', 'sort_order' => 28],
            ['group' => 'field_of_study', 'value' => 'english_language', 'label' => 'زبان انگلیسی', 'sort_order' => 29],
            ['group' => 'field_of_study', 'value' => 'other', 'label' => 'سایر', 'sort_order' => 30],

            // ── disability_type — نوع معلولیت
            ['group' => 'disability_type', 'value' => 'physical', 'label' => 'معلولیت جسمی', 'sort_order' => 1],
            ['group' => 'disability_type', 'value' => 'mental', 'label' => 'معلولیت ذهنی', 'sort_order' => 2],
            ['group' => 'disability_type', 'value' => 'sensory', 'label' => 'معلولیت حسی', 'sort_order' => 3],

            // ── organizational_rank — رده سازمانی
            ['group' => 'organizational_rank', 'value' => 'worker', 'label' => 'کارگر', 'sort_order' => 1],
            ['group' => 'organizational_rank', 'value' => 'employee', 'label' => 'کارمند', 'sort_order' => 2],
            ['group' => 'organizational_rank', 'value' => 'expert', 'label' => 'کارشناس', 'sort_order' => 3],
            ['group' => 'organizational_rank', 'value' => 'senior_expert', 'label' => 'کارشناس ارشد', 'sort_order' => 4],
            ['group' => 'organizational_rank', 'value' => 'mid_manager', 'label' => 'مدیر میانی', 'sort_order' => 5],
            ['group' => 'organizational_rank', 'value' => 'senior_manager', 'label' => 'معاون / مدیر ارشد', 'sort_order' => 6],
            ['group' => 'organizational_rank', 'value' => 'ceo', 'label' => 'مدیرعامل', 'sort_order' => 7],

            // ── language — زبان‌ها
            ['group' => 'language', 'value' => 'persian', 'label' => 'فارسی', 'sort_order' => 1],
            ['group' => 'language', 'value' => 'english', 'label' => 'انگلیسی', 'sort_order' => 2],
            ['group' => 'language', 'value' => 'arabic', 'label' => 'عربی', 'sort_order' => 3],
            ['group' => 'language', 'value' => 'french', 'label' => 'فرانسوی', 'sort_order' => 4],
            ['group' => 'language', 'value' => 'spanish', 'label' => 'اسپانیایی', 'sort_order' => 5],
            ['group' => 'language', 'value' => 'german', 'label' => 'آلمانی', 'sort_order' => 6],
            ['group' => 'language', 'value' => 'italian', 'label' => 'ایتالیایی', 'sort_order' => 7],
            ['group' => 'language', 'value' => 'russian', 'label' => 'روسی', 'sort_order' => 8],
            ['group' => 'language', 'value' => 'japanese', 'label' => 'ژاپنی', 'sort_order' => 9],
            ['group' => 'language', 'value' => 'chinese', 'label' => 'چینی', 'sort_order' => 10],
            ['group' => 'language', 'value' => 'korean', 'label' => 'کره‌ای (هانگول)', 'sort_order' => 11],
            ['group' => 'language', 'value' => 'dutch', 'label' => 'هلندی', 'sort_order' => 12],
            ['group' => 'language', 'value' => 'hindi', 'label' => 'هندی', 'sort_order' => 13],
            ['group' => 'language', 'value' => 'armenian', 'label' => 'ارمنی', 'sort_order' => 14],
            ['group' => 'language', 'value' => 'swedish', 'label' => 'سوئدی', 'sort_order' => 15],
            ['group' => 'language', 'value' => 'finnish', 'label' => 'فنلاندی', 'sort_order' => 16],
            ['group' => 'language', 'value' => 'turkish_istanbul', 'label' => 'ترکی استانبولی', 'sort_order' => 17],
            ['group' => 'language', 'value' => 'azeri', 'label' => 'آذری', 'sort_order' => 18],
            ['group' => 'language', 'value' => 'kurdish', 'label' => 'کردی', 'sort_order' => 19],
            ['group' => 'language', 'value' => 'pashto', 'label' => 'پشتو', 'sort_order' => 20],
            ['group' => 'language', 'value' => 'urdu', 'label' => 'اردو', 'sort_order' => 21],
            ['group' => 'language', 'value' => 'bengali', 'label' => 'بنگالی', 'sort_order' => 22],
            ['group' => 'language', 'value' => 'portuguese', 'label' => 'پرتغالی', 'sort_order' => 23],
            ['group' => 'language', 'value' => 'polish', 'label' => 'لهستانی', 'sort_order' => 24],
            ['group' => 'language', 'value' => 'czech', 'label' => 'چکی', 'sort_order' => 25],
            ['group' => 'language', 'value' => 'hungarian', 'label' => 'مجاری', 'sort_order' => 26],
            ['group' => 'language', 'value' => 'romanian', 'label' => 'رومانیایی', 'sort_order' => 27],
            ['group' => 'language', 'value' => 'bulgarian', 'label' => 'بلغاری', 'sort_order' => 28],
            ['group' => 'language', 'value' => 'serbian', 'label' => 'صربی', 'sort_order' => 29],
            ['group' => 'language', 'value' => 'croatian', 'label' => 'کرواتی', 'sort_order' => 30],
            ['group' => 'language', 'value' => 'ukrainian', 'label' => 'اوکراینی', 'sort_order' => 31],
            ['group' => 'language', 'value' => 'belarusian', 'label' => 'بلاروسی', 'sort_order' => 32],
            ['group' => 'language', 'value' => 'georgian', 'label' => 'گرجی', 'sort_order' => 33],
            ['group' => 'language', 'value' => 'kazakh', 'label' => 'قزاقی', 'sort_order' => 34],
            ['group' => 'language', 'value' => 'uzbek', 'label' => 'ازبکی', 'sort_order' => 35],
            ['group' => 'language', 'value' => 'turkmen', 'label' => 'ترکمنی', 'sort_order' => 36],
            ['group' => 'language', 'value' => 'tajik', 'label' => 'تاجیکی', 'sort_order' => 37],
            ['group' => 'language', 'value' => 'hebrew', 'label' => 'عبری', 'sort_order' => 38],
            ['group' => 'language', 'value' => 'swahili', 'label' => 'سواحیلی', 'sort_order' => 39],
            ['group' => 'language', 'value' => 'danish', 'label' => 'دانمارکی', 'sort_order' => 40],
            ['group' => 'language', 'value' => 'norwegian', 'label' => 'نروژی', 'sort_order' => 41],
            ['group' => 'language', 'value' => 'vietnamese', 'label' => 'ویتنامی', 'sort_order' => 42],
            ['group' => 'language', 'value' => 'thai', 'label' => 'تایلندی', 'sort_order' => 43],
            ['group' => 'language', 'value' => 'malay', 'label' => 'مالایی', 'sort_order' => 44],
            ['group' => 'language', 'value' => 'indonesian', 'label' => 'اندونزیایی', 'sort_order' => 45],

            // ── introduction_method — نحوه آشنایی (گروه‌بندی‌شده با group_label)
            ['group' => 'introduction_method', 'value' => 'job_site', 'label' => 'سایت کاریابی', 'group_label' => 'از طریق آگهی', 'sort_order' => 1],
            ['group' => 'introduction_method', 'value' => 'newspaper_ad', 'label' => 'آگهی استخدام در روزنامه', 'group_label' => 'از طریق آگهی', 'sort_order' => 2],
            ['group' => 'introduction_method', 'value' => 'electronic_ads', 'label' => 'تبلیغات الکترونیکی', 'group_label' => 'از طریق آگهی', 'sort_order' => 3],
            ['group' => 'introduction_method', 'value' => 'company_website', 'label' => 'وب سایت شرکت', 'group_label' => 'از طریق آگهی', 'sort_order' => 4],
            ['group' => 'introduction_method', 'value' => 'elite_foundation', 'label' => 'بنیاد نخبگان', 'group_label' => 'از طریق فراخوان از دانشگاه و موسسات آموزش عالی', 'sort_order' => 5],
            ['group' => 'introduction_method', 'value' => 'university_graduates', 'label' => 'فارغ التحصیلان دانشگاه', 'group_label' => 'از طریق فراخوان از دانشگاه و موسسات آموزش عالی', 'sort_order' => 6],
            ['group' => 'introduction_method', 'value' => 'university_introduction', 'label' => 'معرفی در دانشگاه', 'group_label' => 'از طریق فراخوان از دانشگاه و موسسات آموزش عالی', 'sort_order' => 7],
            ['group' => 'introduction_method', 'value' => 'martyrs_foundation', 'label' => 'بنیاد شهید و امور ایثارگران', 'group_label' => 'از طریق فراخوان از دانشگاه و موسسات آموزش عالی', 'sort_order' => 8],
            ['group' => 'introduction_method', 'value' => 'professional_associations', 'label' => 'انجمن‌های حرفه‌ای / فارغ التحصیلان', 'group_label' => 'از طریق فراخوان از دانشگاه و موسسات آموزش عالی', 'sort_order' => 9],
            ['group' => 'introduction_method', 'value' => 'intern', 'label' => 'کارآموز', 'group_label' => 'از طریق فراخوان از دانشگاه و موسسات آموزش عالی', 'sort_order' => 10],
            ['group' => 'introduction_method', 'value' => 'employment_exam', 'label' => 'آزمون استخدامی', 'group_label' => 'از طریق بانک متقاضیان', 'sort_order' => 11],
            ['group' => 'introduction_method', 'value' => 'company_database', 'label' => 'وبسایت / بانک اطلاعاتی شرکت', 'group_label' => 'از طریق بانک متقاضیان', 'sort_order' => 12],
            ['group' => 'introduction_method', 'value' => 'email_resume', 'label' => 'دریافت رزومه از طریق پست الکترونیک شرکت', 'group_label' => 'از طریق نیروهای متقاضی', 'sort_order' => 13],
            ['group' => 'introduction_method', 'value' => 'internal_referral', 'label' => 'معرفی مدیر مستقیم', 'group_label' => 'از طریق نیروهای متقاضی', 'sort_order' => 14],
            ['group' => 'introduction_method', 'value' => 'internal_transfer', 'label' => 'انتقال داخلی', 'group_label' => 'از طریق نیروهای متقاضی', 'sort_order' => 15],
            ['group' => 'introduction_method', 'value' => 'status_change', 'label' => 'تبدیل وضعیت استخدامی', 'group_label' => 'از طریق نیروهای متقاضی', 'sort_order' => 16],
            ['group' => 'introduction_method', 'value' => 'staffing_company', 'label' => 'شرکت تأمین نیرو', 'group_label' => 'از طریق نیروهای متقاضی', 'sort_order' => 17],
            ['group' => 'introduction_method', 'value' => 'return_former', 'label' => 'بازگشت همکاران سابق', 'group_label' => 'از طریق نیروهای متقاضی', 'sort_order' => 18],
            ['group' => 'introduction_method', 'value' => 'iran_talent', 'label' => 'وب سایت ایران تلنت', 'group_label' => 'از طریق موسسات کاریابی', 'sort_order' => 19],
            ['group' => 'introduction_method', 'value' => 'job_website', 'label' => 'وب سایت کاریابی', 'group_label' => 'از طریق موسسات کاریابی', 'sort_order' => 20],
            ['group' => 'introduction_method', 'value' => 'office_referral', 'label' => 'از طریق دفتر', 'group_label' => 'از طریق موسسات کاریابی', 'sort_order' => 21],
            ['group' => 'introduction_method', 'value' => 'labor_office', 'label' => 'معرفی اداره کار منطقه', 'group_label' => 'از طریق معرف', 'sort_order' => 22],
            ['group' => 'introduction_method', 'value' => 'friend_referral', 'label' => 'معرفی دوستان و آشنایان', 'group_label' => 'از طریق معرف', 'sort_order' => 23],
            ['group' => 'introduction_method', 'value' => 'employee_referral', 'label' => 'معرفی همکاران', 'group_label' => 'از طریق معرف', 'sort_order' => 24],
            ['group' => 'introduction_method', 'value' => 'job_fair', 'label' => 'نمایشگاه کار', 'group_label' => 'سایر', 'sort_order' => 25],
            ['group' => 'introduction_method', 'value' => 'recommended_hiring', 'label' => 'استخدام توصیه‌ای', 'group_label' => 'سایر', 'sort_order' => 26],
            ['group' => 'introduction_method', 'value' => 'in_person', 'label' => 'مراجعه مستقیم / حضوری', 'group_label' => 'سایر', 'sort_order' => 27],
            ['group' => 'introduction_method', 'value' => 'other', 'label' => 'سایر (با ذکر منبع)', 'group_label' => 'سایر', 'sort_order' => 28],
            ['group' => 'introduction_method', 'value' => 'linkedin', 'label' => 'لینکدین (LinkedIn)', 'group_label' => 'از طریق شبکه‌های اجتماعی', 'sort_order' => 29],
            ['group' => 'introduction_method', 'value' => 'social_media', 'label' => 'شبکه‌های اجتماعی (اینستاگرام، تلگرام)', 'group_label' => 'از طریق شبکه‌های اجتماعی', 'sort_order' => 30],
            ['group' => 'introduction_method', 'value' => 'recruitment_event', 'label' => 'رویداد استخدامی / همایش شغلی', 'group_label' => 'سایر', 'sort_order' => 31],

            // ── country — کشور
            ['group' => 'country', 'value' => 'iran', 'label' => 'ایران', 'sort_order' => 1],
            ['group' => 'country', 'value' => 'afghanistan', 'label' => 'افغانستان', 'sort_order' => 2],
            ['group' => 'country', 'value' => 'austria', 'label' => 'اتریش', 'sort_order' => 3],
            ['group' => 'country', 'value' => 'azerbaijan', 'label' => 'آذربایجان', 'sort_order' => 4],
            ['group' => 'country', 'value' => 'armenia', 'label' => 'ارمنستان', 'sort_order' => 5],
            ['group' => 'country', 'value' => 'uzbekistan', 'label' => 'ازبکستان', 'sort_order' => 6],
            ['group' => 'country', 'value' => 'spain', 'label' => 'اسپانیا', 'sort_order' => 7],
            ['group' => 'country', 'value' => 'australia', 'label' => 'استرالیا', 'sort_order' => 8],
            ['group' => 'country', 'value' => 'south_africa', 'label' => 'آفریقای جنوبی', 'sort_order' => 9],
            ['group' => 'country', 'value' => 'algeria', 'label' => 'الجزایر', 'sort_order' => 10],
            ['group' => 'country', 'value' => 'germany', 'label' => 'آلمان', 'sort_order' => 11],
            ['group' => 'country', 'value' => 'uae', 'label' => 'امارات متحده عربی', 'sort_order' => 12],
            ['group' => 'country', 'value' => 'usa', 'label' => 'آمریکا', 'sort_order' => 13],
            ['group' => 'country', 'value' => 'indonesia', 'label' => 'اندونزی', 'sort_order' => 14],
            ['group' => 'country', 'value' => 'uk', 'label' => 'انگلستان', 'sort_order' => 15],
            ['group' => 'country', 'value' => 'ukraine', 'label' => 'اوکراین', 'sort_order' => 16],
            ['group' => 'country', 'value' => 'italy', 'label' => 'ایتالیا', 'sort_order' => 17],
            ['group' => 'country', 'value' => 'ireland', 'label' => 'ایرلند', 'sort_order' => 18],
            ['group' => 'country', 'value' => 'brazil', 'label' => 'برزیل', 'sort_order' => 19],
            ['group' => 'country', 'value' => 'belarus', 'label' => 'بلاروس', 'sort_order' => 20],
            ['group' => 'country', 'value' => 'belgium', 'label' => 'بلژیک', 'sort_order' => 21],
            ['group' => 'country', 'value' => 'bangladesh', 'label' => 'بنگلادش', 'sort_order' => 22],
            ['group' => 'country', 'value' => 'burkina_faso', 'label' => 'بورکینافاسو', 'sort_order' => 23],
            ['group' => 'country', 'value' => 'pakistan', 'label' => 'پاکستان', 'sort_order' => 24],
            ['group' => 'country', 'value' => 'portugal', 'label' => 'پرتغال', 'sort_order' => 25],
            ['group' => 'country', 'value' => 'tanzania', 'label' => 'تانزانیا', 'sort_order' => 26],
            ['group' => 'country', 'value' => 'thailand', 'label' => 'تایلند', 'sort_order' => 27],
            ['group' => 'country', 'value' => 'turkmenistan', 'label' => 'ترکمنستان', 'sort_order' => 28],
            ['group' => 'country', 'value' => 'turkey', 'label' => 'ترکیه', 'sort_order' => 29],
            ['group' => 'country', 'value' => 'tunisia', 'label' => 'تونس', 'sort_order' => 30],
            ['group' => 'country', 'value' => 'czech_republic', 'label' => 'جمهوری چک', 'sort_order' => 31],
            ['group' => 'country', 'value' => 'china', 'label' => 'چین', 'sort_order' => 32],
            ['group' => 'country', 'value' => 'russia', 'label' => 'روسیه', 'sort_order' => 33],
            ['group' => 'country', 'value' => 'romania', 'label' => 'رومانی', 'sort_order' => 34],
            ['group' => 'country', 'value' => 'japan', 'label' => 'ژاپن', 'sort_order' => 35],
            ['group' => 'country', 'value' => 'singapore', 'label' => 'سنگاپور', 'sort_order' => 36],
            ['group' => 'country', 'value' => 'senegal', 'label' => 'سنگال', 'sort_order' => 37],
            ['group' => 'country', 'value' => 'syria', 'label' => 'سوریه', 'sort_order' => 38],
            ['group' => 'country', 'value' => 'sweden', 'label' => 'سوئد', 'sort_order' => 39],
            ['group' => 'country', 'value' => 'switzerland', 'label' => 'سوئیس', 'sort_order' => 40],
            ['group' => 'country', 'value' => 'iraq', 'label' => 'عراق', 'sort_order' => 41],
            ['group' => 'country', 'value' => 'oman', 'label' => 'عمان', 'sort_order' => 42],
            ['group' => 'country', 'value' => 'ghana', 'label' => 'غنا', 'sort_order' => 43],
            ['group' => 'country', 'value' => 'france', 'label' => 'فرانسه', 'sort_order' => 44],
            ['group' => 'country', 'value' => 'finland', 'label' => 'فنلاند', 'sort_order' => 45],
            ['group' => 'country', 'value' => 'philippines', 'label' => 'فیلیپین', 'sort_order' => 46],
            ['group' => 'country', 'value' => 'cyprus', 'label' => 'قبرس', 'sort_order' => 47],
            ['group' => 'country', 'value' => 'kazakhstan', 'label' => 'قزاقستان', 'sort_order' => 48],
            ['group' => 'country', 'value' => 'qatar', 'label' => 'قطر', 'sort_order' => 49],
            ['group' => 'country', 'value' => 'canada', 'label' => 'کانادا', 'sort_order' => 50],
            ['group' => 'country', 'value' => 'south_korea', 'label' => 'کره جنوبی', 'sort_order' => 51],
            ['group' => 'country', 'value' => 'croatia', 'label' => 'کرواسی', 'sort_order' => 52],
            ['group' => 'country', 'value' => 'kenya', 'label' => 'کنیا', 'sort_order' => 53],
            ['group' => 'country', 'value' => 'kuwait', 'label' => 'کویت', 'sort_order' => 54],
            ['group' => 'country', 'value' => 'laos', 'label' => 'لائوس', 'sort_order' => 55],
            ['group' => 'country', 'value' => 'lebanon', 'label' => 'لبنان', 'sort_order' => 56],
            ['group' => 'country', 'value' => 'poland', 'label' => 'لهستان', 'sort_order' => 57],
            ['group' => 'country', 'value' => 'libya', 'label' => 'لیبی', 'sort_order' => 58],
            ['group' => 'country', 'value' => 'malaysia', 'label' => 'مالزی', 'sort_order' => 59],
            ['group' => 'country', 'value' => 'hungary', 'label' => 'مجارستان', 'sort_order' => 60],
            ['group' => 'country', 'value' => 'north_macedonia', 'label' => 'مقدونیه شمالی', 'sort_order' => 61],
            ['group' => 'country', 'value' => 'mozambique', 'label' => 'موزامبیک', 'sort_order' => 62],
            ['group' => 'country', 'value' => 'unknown', 'label' => 'نامشخص', 'sort_order' => 63],
            ['group' => 'country', 'value' => 'norway', 'label' => 'نروژ', 'sort_order' => 64],
            ['group' => 'country', 'value' => 'nigeria', 'label' => 'نیجریه', 'sort_order' => 65],
            ['group' => 'country', 'value' => 'netherlands', 'label' => 'هلند', 'sort_order' => 66],
            ['group' => 'country', 'value' => 'india', 'label' => 'هند', 'sort_order' => 67],
            ['group' => 'country', 'value' => 'venezuela', 'label' => 'ونزوئلا', 'sort_order' => 68],
            ['group' => 'country', 'value' => 'greece', 'label' => 'یونان', 'sort_order' => 69],
            ['group' => 'country', 'value' => 'egypt', 'label' => 'مصر', 'sort_order' => 70],
            ['group' => 'country', 'value' => 'saudi_arabia', 'label' => 'عربستان سعودی', 'sort_order' => 71],
            ['group' => 'country', 'value' => 'bahrain', 'label' => 'بحرین', 'sort_order' => 72],
            ['group' => 'country', 'value' => 'jordan', 'label' => 'اردن', 'sort_order' => 73],
            ['group' => 'country', 'value' => 'yemen', 'label' => 'یمن', 'sort_order' => 74],
            ['group' => 'country', 'value' => 'new_zealand', 'label' => 'نیوزیلند', 'sort_order' => 75],
            ['group' => 'country', 'value' => 'denmark', 'label' => 'دانمارک', 'sort_order' => 76],
            ['group' => 'country', 'value' => 'slovakia', 'label' => 'اسلواکی', 'sort_order' => 77],
            ['group' => 'country', 'value' => 'slovenia', 'label' => 'اسلوونی', 'sort_order' => 78],
            ['group' => 'country', 'value' => 'bulgaria', 'label' => 'بلغارستان', 'sort_order' => 79],
            ['group' => 'country', 'value' => 'serbia', 'label' => 'صربستان', 'sort_order' => 80],
            ['group' => 'country', 'value' => 'bosnia', 'label' => 'بوسنی و هرزگوین', 'sort_order' => 81],
            ['group' => 'country', 'value' => 'albania', 'label' => 'آلبانی', 'sort_order' => 82],
            ['group' => 'country', 'value' => 'colombia', 'label' => 'کلمبیا', 'sort_order' => 83],
            ['group' => 'country', 'value' => 'argentina', 'label' => 'آرژانتین', 'sort_order' => 84],
            ['group' => 'country', 'value' => 'chile', 'label' => 'شیلی', 'sort_order' => 85],
            ['group' => 'country', 'value' => 'mexico', 'label' => 'مکزیک', 'sort_order' => 86],
            ['group' => 'country', 'value' => 'peru', 'label' => 'پرو', 'sort_order' => 87],
            ['group' => 'country', 'value' => 'ecuador', 'label' => 'اکوادور', 'sort_order' => 88],
            ['group' => 'country', 'value' => 'sri_lanka', 'label' => 'سریلانکا', 'sort_order' => 89],
            ['group' => 'country', 'value' => 'nepal', 'label' => 'نپال', 'sort_order' => 90],
            ['group' => 'country', 'value' => 'myanmar', 'label' => 'میانمار', 'sort_order' => 91],
            ['group' => 'country', 'value' => 'cambodia', 'label' => 'کامبوج', 'sort_order' => 92],
            ['group' => 'country', 'value' => 'vietnam', 'label' => 'ویتنام', 'sort_order' => 93],
            ['group' => 'country', 'value' => 'georgia', 'label' => 'گرجستان', 'sort_order' => 94],
            ['group' => 'country', 'value' => 'tajikistan', 'label' => 'تاجیکستان', 'sort_order' => 95],
            ['group' => 'country', 'value' => 'kyrgyzstan', 'label' => 'قرقیزستان', 'sort_order' => 96],
            ['group' => 'country', 'value' => 'moldova', 'label' => 'مولداوی', 'sort_order' => 97],
            ['group' => 'country', 'value' => 'lithuania', 'label' => 'لیتوانی', 'sort_order' => 98],
            ['group' => 'country', 'value' => 'latvia', 'label' => 'لتونی', 'sort_order' => 99],
            ['group' => 'country', 'value' => 'estonia', 'label' => 'استونی', 'sort_order' => 100],
            ['group' => 'country', 'value' => 'iceland', 'label' => 'ایسلند', 'sort_order' => 101],
            ['group' => 'country', 'value' => 'luxembourg', 'label' => 'لوکزامبورگ', 'sort_order' => 102],
            ['group' => 'country', 'value' => 'monaco', 'label' => 'موناکو', 'sort_order' => 103],
            ['group' => 'country', 'value' => 'malta', 'label' => 'مالت', 'sort_order' => 104],
            ['group' => 'country', 'value' => 'morocco', 'label' => 'مراکش', 'sort_order' => 105],
            ['group' => 'country', 'value' => 'sudan', 'label' => 'سودان', 'sort_order' => 106],
            ['group' => 'country', 'value' => 'ethiopia', 'label' => 'اتیوپی', 'sort_order' => 107],
            ['group' => 'country', 'value' => 'uganda', 'label' => 'اوگاندا', 'sort_order' => 108],
            ['group' => 'country', 'value' => 'cameroon', 'label' => 'کامرون', 'sort_order' => 109],
            ['group' => 'country', 'value' => 'ivory_coast', 'label' => 'ساحل عاج', 'sort_order' => 110],
            ['group' => 'country', 'value' => 'zimbabwe', 'label' => 'زیمبابوه', 'sort_order' => 111],
            ['group' => 'country', 'value' => 'zambia', 'label' => 'زامبیا', 'sort_order' => 112],
            ['group' => 'country', 'value' => 'angola', 'label' => 'آنگولا', 'sort_order' => 113],
            ['group' => 'country', 'value' => 'congo', 'label' => 'کنگو', 'sort_order' => 114],
            ['group' => 'country', 'value' => 'madagascar', 'label' => 'ماداگاسکار', 'sort_order' => 115],
            ['group' => 'country', 'value' => 'cuba', 'label' => 'کوبا', 'sort_order' => 116],
            ['group' => 'country', 'value' => 'panama', 'label' => 'پاناما', 'sort_order' => 117],
            ['group' => 'country', 'value' => 'costa_rica', 'label' => 'کاستاریکا', 'sort_order' => 118],
            ['group' => 'country', 'value' => 'uruguay', 'label' => 'اروگوئه', 'sort_order' => 119],
            ['group' => 'country', 'value' => 'paraguay', 'label' => 'پاراگوئه', 'sort_order' => 120],
            ['group' => 'country', 'value' => 'bolivia', 'label' => 'بولیوی', 'sort_order' => 121],
            ['group' => 'country', 'value' => 'guatemala', 'label' => 'گواتمالا', 'sort_order' => 122],
            ['group' => 'country', 'value' => 'dominican_republic', 'label' => 'جمهوری دومینیکن', 'sort_order' => 123],
            ['group' => 'country', 'value' => 'jamaica', 'label' => 'جامائیکا', 'sort_order' => 124],
            ['group' => 'country', 'value' => 'trinidad', 'label' => 'ترینیداد و توباگو', 'sort_order' => 125],
            ['group' => 'country', 'value' => 'brunei', 'label' => 'برونئی', 'sort_order' => 126],
            ['group' => 'country', 'value' => 'east_timor', 'label' => 'تیمور شرقی', 'sort_order' => 127],
            ['group' => 'country', 'value' => 'mongolia', 'label' => 'مغولستان', 'sort_order' => 128],
            ['group' => 'country', 'value' => 'north_korea', 'label' => 'کره شمالی', 'sort_order' => 129],
            ['group' => 'country', 'value' => 'maldives', 'label' => 'مالدیو', 'sort_order' => 130],
            ['group' => 'country', 'value' => 'bhutan', 'label' => 'بوتان', 'sort_order' => 131],
            ['group' => 'country', 'value' => 'somalia', 'label' => 'سومالی', 'sort_order' => 132],
            ['group' => 'country', 'value' => 'mauritius', 'label' => 'موریس', 'sort_order' => 133],
            ['group' => 'country', 'value' => 'seychelles', 'label' => 'سیشل', 'sort_order' => 134],
            ['group' => 'country', 'value' => 'palestine', 'label' => 'فلسطین', 'sort_order' => 135],
            ['group' => 'country', 'value' => 'kosovo', 'label' => 'کوزوو', 'sort_order' => 136],
            ['group' => 'country', 'value' => 'montenegro', 'label' => 'مونته‌نگرو', 'sort_order' => 137],
        ];
    }

    public function run(?array $groups = null): void
    {
        foreach ($this->options() as $option) {
            if ($groups !== null && ! in_array($option['group'], $groups, true)) {
                continue;
            }

            FormOption::updateOrCreate(
                ['group' => $option['group'], 'value' => $option['value']],
                $option,
            );
        }
    }
}
