import type { SubmitValidationResult } from "@/lib/submit-validation";

export {
    buildSubmitSchema,
    buildSubmitValidator,
    type SubmitOptions,
    type SubmitFormData,
    buildPersonalInfoSchemas,
    type PersonalInfoOptions,
    type PersonalInfoSchemas,
    buildJobRequestSchemas,
    type JobRequestOptions,
    type JobRequestSchemas,
    contactInfoFieldSchema,
    contactInfoFieldSchemas,
    educationFieldSchema,
    educationFieldSchemas,
    educationRecordSchema,
    workExperienceFieldSchema,
    workExperienceFieldSchemas,
    workExperienceRecordSchema,
    skillsFieldSchema,
    skillsFieldSchemas,
    languageSkillSchema,
    softwareSkillSchema,
    certificateSchema,
    trainingFieldSchema,
    trainingFieldSchemas,
    trainingCourseSchema,
    researchSchema,
    additionalInfoFieldSchema,
    additionalInfoFieldSchemas,
    referenceSchema,
    addressSchema,
} from "./schemas";

export type { SubmitValidationResult };
